#!/usr/bin/env bash

set -e

setProxyMode() {

  echo "[INFO] Set Proxy mode...";

  echo "[INFO] Install nginx...";
  apk add nginx nginx-mod-stream
  echo "";

  [ ! -z "$DNS_SERVER" ] || export DNS_SERVER=$(awk '/nameserver/{a=(a?a" "$2:$2)} END{print a}' /etc/resolv.conf 2> /dev/null)

  echo "[INFO] Generate nginx configuration...";
  existHosts="false";
  servers=""
  for key in "${!PROXY_HOST_@}"; do
      declare -n value=$key
      port="${key/PROXY_HOST_/}"
      # echo "$port"
      # echo "$value"
      existHosts="true";

      host_parts=($(echo "$value" | tr ':' '\n'))
      servers+="
      server {
          resolver $DNS_SERVER ipv6=off valid=30s;
          listen ${port};
          set \$server${port} ${host_parts[0]}:${host_parts[1]}
          proxy_pass \$server${port};
      }
      "
  done

  if [ "$existHosts" == "false" ]; then
    echo "[ERROR!] Cannot find PROXY_HOST_* environment variables!"
    exit 1
  fi


  echo "
  # /etc/nginx/nginx.conf
  user nginx;
  worker_processes auto;
  error_log /var/log/nginx/error.log warn;
  include /etc/nginx/modules/*.conf;

  events {
          worker_connections 1024;
  }

  stream {
    $servers
  }" > /etc/nginx/nginx.conf
  cat /etc/nginx/nginx.conf
}

runProxy() {
  if [ "$PROXY_MODE" == "true" ]; then
    nginx -g "daemon off;error_log /dev/stdout info;"
  fi
}


up() {
  sleep 5

  if [ "$SET_IP_FORWARD" == "true" ]; then
    echo "[INFO] Set net.ipv4.ip_forward = 1 ...";
    echo 'net.ipv4.ip_forward = 1' | tee -a /etc/sysctl.conf;
    sysctl -p /etc/sysctl.conf;
  fi

  tailscale up \
    --accept-dns=${TAILSCALE_ACCEPT_DNS:-true} \
    --accept-routes=${TAILSCALE_ACCEPT_ROUTES:-false} \
    --advertise-exit-node=${TAILSCALE_ADVERTISE_EXIT_NODE:-false} \
    --advertise-routes=${TAILSCALE_ADVERTISE_ROUTES} \
    --advertise-tags=${TAILSCALE_ADVERTISE_TAGS} \
    --authkey=${TAILSCALE_AUTH_KEY} \
    --exit-node-allow-lan-access=${TAILSCALE_EXIT_NODE_ALLOW_LAN_ACCESS:-false} \
    --exit-node=${TAILSCALE_EXIT_NODE} \
    --force-reauth=${TAILSCALE_FORCE_REAUTH:-false} \
    --host-routes=${TAILSCALE_HOST_ROUTES:-true} \
    --hostname=${TAILSCALE_HOSTNAME:-$(hostname)} \
    --login-server=${TAILSCALE_LOGIN_SERVER:-"https://login.tailscale.com"} \
    --netfilter-mode=${TAILSCALE_NETFILTER_MODE:-on} \
    --qr=${TAILSCALE_QR:-false} \
    --shields-up=${TAILSCALE_SHIELDS_UP:-false} \
    --snat-subnet-routes=${TAILSCALE_SNAT_SUBNET_ROUTES:-true}
}

if [ ! -d /dev/net ]; then mkdir /dev/net; fi
if [ ! -e /dev/net/tun ]; then mknod /dev/net/tun c 10 200; fi

if [ "$PROXY_MODE" == "true" ]; then
  setProxyMode
fi

runProxy & up & tailscaled \
  -port ${TAILSCALED_PORT:-0} \
  -socket ${TAILSCALED_SOCKET:-"/var/run/tailscale/tailscaled.sock"} \
  -state ${TAILSCALED_STATE:-"/var/lib/tailscale/tailscaled.state"} \
  -tun ${TAILSCALED_TUN:-"tailscale0"} \
  -verbose ${TAILSCALED_VERBOSE:-0}
